//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformanceChecks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PerformanceChecks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200
        ///0 0 0
        ///0.0054216 0.11349 0.040749
        ///-0.0017447 0.11425 0.041273
        ///-0.010661 0.11338 0.040916
        ///0.026422 0.11499 0.032623
        ///0.024545 0.12284 0.024255
        ///0.034137 0.11316 0.02507
        ///0.02886 0.11773 0.027037
        ///0.02675 0.12234 0.017605
        ///0.03575 0.1123 0.019109
        ///0.015982 0.12307 0.031279
        ///0.0079813 0.12438 0.032798
        ///0.018101 0.11674 0.035493
        ///0.0086687 0.11758 0.037538
        ///0.01808 0.12536 0.026132
        ///0.0080861 0.12866 0.02619
        ///0.02275 0.12146 0.029671
        ///-0.0018689 0.12456 0.033184
        ///-0.011168 0.12376 0.032519
        ///-0.0020063 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bunny2 {
            get {
                return ResourceManager.GetString("bunny2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 361
        ///0 0 0
        ///0.053026 0.11349 0.077131
        ///0.051684 0.12201 0.066413
        ///0.062 0.11265 0.066529
        ///0.055908 0.1166 0.069704
        ///0.042443 0.12161 0.075045
        ///0.035388 0.12182 0.075395
        ///0.045215 0.11564 0.07963
        ///0.035383 0.11586 0.080111
        ///0.045076 0.12398 0.06937
        ///0.035184 0.12594 0.069924
        ///0.049096 0.11996 0.073017
        ///0.028054 0.12158 0.074732
        ///0.025599 0.11552 0.077258
        ///0.017576 0.11347 0.07555
        ///0.025395 0.12495 0.0696
        ///0.016659 0.12306 0.067178
        ///0.021547 0.11966 0.073101
        ///0.014291 0.11718 0.071342
        ///0.025508 0.16152 0.0247 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bunny4 {
            get {
                return ResourceManager.GetString("bunny4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 729077
        ///0 0 0
        ///-0.091424 -0.272159 -1.463130 
        ///-0.092167 -0.283904 -1.460720 
        ///-0.094234 -0.295696 -1.460950 
        ///-0.134843 -0.330655 -1.472900 
        ///-0.097615 -0.240535 -1.438410 
        ///-0.101719 -0.240558 -1.444240 
        ///-0.087747 -0.256648 -1.437310 
        ///-0.089671 -0.265442 -1.450820 
        ///-0.093918 -0.288727 -1.450890 
        ///-0.088284 -0.282376 -1.439640 
        ///-0.089870 -0.277789 -1.450290 
        ///-0.063862 -0.224043 -1.426390 
        ///-0.067949 -0.239861 -1.426040 
        ///-0.056452 -0.251687 -1.424660 
        ///-0.060890 -0.262222 -1.426020 
        ///-0.023479 -0.2474 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string owl_clean3 {
            get {
                return ResourceManager.GetString("owl_clean3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 753870
        ///0 0 0
        ///-0.091424 -0.272159 -1.463130 
        ///-0.092167 -0.283904 -1.460720 
        ///-0.094234 -0.295696 -1.460950 
        ///-0.134843 -0.330655 -1.472900 
        ///-0.097615 -0.240535 -1.438410 
        ///-0.101719 -0.240558 -1.444240 
        ///-0.087747 -0.256648 -1.437310 
        ///-0.089671 -0.265442 -1.450820 
        ///-0.093918 -0.288727 -1.450890 
        ///-0.088284 -0.282376 -1.439640 
        ///-0.089870 -0.277789 -1.450290 
        ///-0.063862 -0.224043 -1.426390 
        ///-0.067949 -0.239861 -1.426040 
        ///-0.056452 -0.251687 -1.424660 
        ///-0.060890 -0.262222 -1.426020 
        ///-0.023479 -0.2474 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string owl_clean4 {
            get {
                return ResourceManager.GetString("owl_clean4", resourceCulture);
            }
        }
    }
}
